### ISSUE TITLE
Is it possible to use this with Ace Perms? I would like to add some sounds for our medics and law enforcement but don't want random people running around playing sounds non stop

### ISSUE THREAD

**Issue by ResqDiver1317** [LondonStudios/SmartSounds#1]

**Comment by LondonStudios** [comment]
Hi,

This is a feature I am happy to add and I will do so soon.

Best wishes,
London Studios

**Comment by LondonStudios** [comment]
Hi,

Going to be closing this however this will be implemented soon.

Best wishes,
London Studios
